question_data_history_easy = [
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "In World War ll, Great Britain used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Thomas Crapper was a plumber who invented the flushing toilet.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
                                      "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The Cold War ended with Joseph Stalin&#039;s death.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    ]
question_data_sports_easy = [
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
     "question": "Shaquille O&rsquo;Neal has only made one three pointer in his career.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
                                       "question": "Roger Federer is a famous soccer player.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
     "question": "Peyton Manning retired after winning Super Bowl XLIX.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
                                      "question": "There are a total of 20 races in Formula One 2016 season.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
     "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
]
question_data_animals_easy = [
    {"type": "boolean", "difficulty": "easy", "category": "Animals", "question": "Rabbits are carnivores.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "A flock of crows is known as a homicide.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "Kangaroos keep food in their pouches next to their children.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "The freshwater amphibian, the Axolotl, can regrow it;s limbs.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
]
question_data_gk_easy = [
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Dihydrogen Monoxide is a dangerous chemical.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                      "question": "Ping-Pong originated in England", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge", "question": "Pluto is a planet.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
]
question_data_movie_easy = [
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
]
question_data_history_hard = [
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The Kingdom of Prussia briefly held land in Estonia.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
                                      "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The USS Missouri (BB-63) last served in the Korean War.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
                                      "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland&#039;s.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The Battle of Trafalgar took place on October 23rd, 1805", "correct_answer": "False",
     "incorrect_answers": ["True"]},
]
question_data_sports_hard = [
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                      "question": "Tennis was once known as Racquetball.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                      "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                      "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                      "question": "The first episode of WWF Monday Night RAW aired on January 11, 1990.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                      "question": "The Olympics tennis court is a giant green screen.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
]
question_data_animals_hard = [
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "Finnish Lapphund dogs were used for herding reindeer.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
                                       "question": "An octopus can fit through any hole larger than its beak.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "Tigers have one colour of skin despite the stripey fur.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
                                      "question": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
]
question_data_gk_hard = [
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
     "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
     "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
     "question": "In Scandinavian languages, the letter &Aring; means river.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
                                       "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
     "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
]
question_data_movie_hard = [
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The movie &quot;The Rocky Horror Picture Show&quot; (1975) opens with giant floating lips singing the opening song",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                                      "question": "The color of the pills in the Matrix were Blue and Yellow.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
]

easy = [question_data_history_easy, question_data_animals_easy, question_data_sports_easy, question_data_movie_easy, question_data_gk_easy]
hard = [question_data_history_hard, question_data_animals_hard, question_data_sports_hard, question_data_movie_hard, question_data_gk_hard]